# Site settings
title: Big WHY
email: mzb@BigWhy.pro
description: Discern your BigWhy. First, focus on causal inference; then reverse engineer, prioritize, study causal lesser WHYs as you clarify your BigWhy. Repeat to sculpt.
twitter_username: MarkBruns
github_username:  BigWhyPro

# Build settings
markdown: kramdown
