# Site settings
title: Big WHY
email: mzb@BigWhy.pro
description: KNOWING your WHY ... EXPLORING the FULL Ishikawa of ten different causal drivers to at least five levels of WHY
twitter_username: MarkBruns
github_username:  BigWhyPro

# Build settings
markdown: kramdown
