# Site settings
title: Big WHY
email: mzb@BigWhy.pro
description: KNOW your WHY ... that means the FULL Ishikawa cause-and-effect diagram for multiple facets of that WHY and at least five levels of WHY for each facet's branch
twitter_username: MarkBruns
github_username:  BigWhyPro

# Build settings
markdown: kramdown
