# Site settings
title: Big WHY
email: mzb@BigWhy.pro
description: Discern your BigWhy ... first, focus causal inference ... then reverse engineer, prioritize and study the causal lesser WHYs as you clarify your BigWhy. Repeat.
twitter_username: MarkBruns
github_username:  BigWhyPro

# Build settings
markdown: kramdown
