# Site settings
title: Big WHY
email: mzb@BigWhy.pro
description: BigWhyAI is a tool that sells someone their own dream ~on commission~ by helping them to better discern their own Big WHY and how to build the tools from the energy and talent they have.
twitter_username: MarkBruns
github_username:  BigWhyPro

# Build settings
markdown: kramdown
