# Site settings
title: Big WHY
email: mzb@BigWhy.pro
description: KNOWING your WHY...means that you are continually journalling and re-mapping out the FULL Ishikawa cause-and-effect diagram for multiple facets of that WHY and at least five levels of WHY for each and every facet's branch
twitter_username: MarkBruns
github_username:  BigWhyPro

# Build settings
markdown: kramdown
